sudo: required

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

install:
  - docker build --pull -t bdevloed/eyeserver .
  
script:
- docker push bdevloed/eyeserver
